### PR TITLE
Added reverse compatibility with DSM 5.2

### PR DESCRIPTION
**Pull request by aaska**
I don't know very much Python, but I've adapted the class to add compatibility with DSM 5.x versions.

My code seems very dirty, but basically it has a different endpoint to retrieve volumes and disks data on 5.x and the class needs to be updated as there is no root data object in the previous endpoint.

Let me know if you need any additional information

### CODE REVIEW

**Comment by StaticCube** [comment]
Very Nice, I might have a friend which is able to run a test as well on DSM 5. Code is looking fine :-) ( was only able to check from my phone but still).

**Comment by aaska** [comment]
I did some changes to try to clean things up a bit and added some documentation on this !

**Comment by StaticCube** [comment]
Checked implementation statically (sadly no access to dsm 5). No issues detected, tested version against DSM 6 (which didn't pose any problems). Merging

**Comment by StaticCube** [comment]
Has been merged in version 0.4.0 :)

**Pull request merged**
