### PR TITLE
Make _get_url actually returning a response when retry_on_error=True

### PR DESCRIPTION
**Pull request by Quentame**
Addressed this issue : https://github.com/home-assistant/home-assistant/pull/30720#discussion_r365761989

### CODE REVIEW

**Comment by StaticCube** [comment]
Nice one, will test this one out tonight (looking at the code everything should work fine), after that i will merge the request. 

Hopefully end of this week i will also be able  to create a new pipy package, so the home assistant could be updated.

Ferry

**Comment by Quentame** [comment]
Hi @StaticCube !
Did you have time to look at it ?

**Comment by StaticCube** [comment]
Hi @Quentame, AM actually testing it out at the moment (crazy weekend 🙂), looks good. Will merge within the hour

**Comment by StaticCube** [comment]
Has been merged in version 0.4.0 :)

**Comment by Quentame** [comment]
Thanks 😉

**Pull request merged**
