### PR TITLE
Update SynologyDSM.py

### PR DESCRIPTION
**Pull request by kuchel77**
This fixes the average temperature and maximum temperature for the disks. It fixes the functions not being able to find any disks.

### CODE REVIEW

**Comment by StaticCube** [comment]
Nice thank you very much

**Comment by Quentame** [comment]
@StaticCube can you realease the library ?

So it will fix https://github.com/home-assistant/home-assistant/issues/26945

Thanks

**Comment by Mariusthvdb** [comment]
please do, it is a long waiting fix..thanks for speeding up if you would!

**Comment by StaticCube** [comment]
Site thing, will do it tonight.

**Comment by StaticCube** [comment]
Done, version is bumped to version 0.3.0 so it can be submitted to home assistant

**Comment by Quentame** [comment]
I does not see any 0.3.0 in the [release page](https://github.com/StaticCube/python-synology/releases)

**Comment by StaticCube** [comment]
Your right didn't upload that one yet, Will do that tomorrow. But it is uploaded to pypi (which provided the pip python packages). https://pypi.org/project/python-synology/#history

**Comment by Mariusthvdb** [comment]
so will this be an automatic update then, or do we need to wait for HA to update this into core?

**Comment by StaticCube** [comment]
Nope not automatically but updates the version in home assistant so when accepted should be in the next release (pull request #30528)

**Comment by Mariusthvdb** [comment]
ok cool, thanks a bunch!

**Pull request merged**
